version: '3'

services:
    db:
        image: 'postgres:11'
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=h5
            - POSTGRES_USER=h5
            - POSTGRES_DB=h5
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - 8080:80
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
